
export
    LIBPOSTPROC_VERSION_MAJOR,
    LIBPOSTPROC_VERSION_MINOR,
    LIBPOSTPROC_VERSION_MICRO,
    LIBPOSTPROC_BUILD,
    PP_QUALITY_MAX,
    QP_STORE_T,
    PP_CPU_CAPS_MMX,
    PP_CPU_CAPS_MMX2,
    PP_CPU_CAPS_3DNOW,
    PP_CPU_CAPS_ALTIVEC,
    PP_FORMAT,
    PP_FORMAT_420,
    PP_FORMAT_422,
    PP_FORMAT_411,
    PP_FORMAT_444,
    PP_PICT_TYPE_QP2,
    pp_context,
    pp_mode


const LIBPOSTPROC_VERSION_MAJOR = 52
const LIBPOSTPROC_VERSION_MINOR = 0
const LIBPOSTPROC_VERSION_MICRO = 100

# Skipping MacroDefinition: LIBPOSTPROC_VERSION_INT AV_VERSION_INT ( LIBPOSTPROC_VERSION_MAJOR , LIBPOSTPROC_VERSION_MINOR , LIBPOSTPROC_VERSION_MICRO )
# Skipping MacroDefinition: LIBPOSTPROC_VERSION AV_VERSION ( LIBPOSTPROC_VERSION_MAJOR , LIBPOSTPROC_VERSION_MINOR , LIBPOSTPROC_VERSION_MICRO )

const LIBPOSTPROC_BUILD = LIBPOSTPROC_VERSION_INT

# Skipping MacroDefinition: LIBPOSTPROC_IDENT "postproc" AV_STRINGIFY ( LIBPOSTPROC_VERSION )

const PP_QUALITY_MAX = 6
const QP_STORE_T = int8_t
const PP_CPU_CAPS_MMX = 0x80000000
const PP_CPU_CAPS_MMX2 = 0x20000000
const PP_CPU_CAPS_3DNOW = 0x40000000
const PP_CPU_CAPS_ALTIVEC = 0x10000000
const PP_FORMAT = 0x00000008
const PP_FORMAT_420 = 0x00000011 | PP_FORMAT
const PP_FORMAT_422 = 0x00000001 | PP_FORMAT
const PP_FORMAT_411 = 0x00000002 | PP_FORMAT
const PP_FORMAT_444 = 0x00000000 | PP_FORMAT
const PP_PICT_TYPE_QP2 = 0x00000010

typealias pp_context Void
typealias pp_mode Void
