local Pipeline(name, image) = {
  kind: "pipeline",
  name: name,
  platform: {
    os: "linux",
    arch: "arm",
  },
  steps: [
    {
      name: "build",
      image: image,
      commands: [
        "julia -e using Pkg; Pkg.clone(pwd()); Pkg.build("VideoIO"); Pkg.test("VideoIO"; coverage=true)'"
      ]
    }
  ]
};

[
  Pipeline("julia-arm-1-0", "julia:1.0"),
  Pipeline("julia-arm-1-1", "julia:1.1"),
]
