kind: pipeline
name: linux-$(ARCH_VERSION)-$(JULIA_VERSION)

platform:
  os: linux
  arch: $(ARCH_VERSION)

steps:
- name: build
  image: julia:$(JULIA_VERSION)
  commands:
      - uname -a
      - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("VideoIO"); Pkg.test("VideoIO"; coverage=true)'

matrix:
  JULIA_VERSION:
    - 1.0
    - 1.1
  ARCH_VERSION:
    - arm
    - arm64
