kind: pipeline
name: linux-arm-1.3

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: julia:1.3
  commands:
      - uname -a
      - julia --project=. -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

---

kind: pipeline
name: linux-arm-1.3

platform:
 os: linux
 arch: arm

steps:
- name: build
 image: julia:1.3
 commands:
     - uname -a
     - julia --project=. -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
