kind: pipeline
name: linux-arm-1.0

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: julia:1.0
  commands:
      - uname -a
      - apt-get update && apt-get install -qy build-essential hdf5-tools
      - julia --project=. -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

#---
#
#kind: pipeline
#name: linux-arm-1.1
#
#platform:
#  os: linux
#  arch: arm
#
#steps:
#- name: build
#  image: julia:1.1
#  commands:
      - uname -a
      - apt-get update && apt-get install -qy build-essential hdf5-tools
      - julia --project=. -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

---

kind: pipeline
name: linux-aarch64-1.0

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: julia:1.0
  commands:
      - uname -a
      - apt-get update && apt-get install -qy build-essential hdf5-tools
      - julia --project=. -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

---

kind: pipeline
name: linux-aarch64-1.1

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: julia:1.1
  commands:
      - uname -a
      - apt-get update && apt-get install -qy build-essential hdf5-tools
      - julia --project=. -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
