
export
    SWR_CH_MAX,
    SWR_FLAG_RESAMPLE,
    SwrDitherType,
    SWR_DITHER_NONE,
    SWR_DITHER_RECTANGULAR,
    SWR_DITHER_TRIANGULAR,
    SWR_DITHER_TRIANGULAR_HIGHPASS,
    SWR_DITHER_NS,
    SWR_DITHER_NS_LIPSHITZ,
    SWR_DITHER_NS_F_WEIGHTED,
    SWR_DITHER_NS_MODIFIED_E_WEIGHTED,
    SWR_DITHER_NS_IMPROVED_E_WEIGHTED,
    SWR_DITHER_NS_SHIBATA,
    SWR_DITHER_NS_LOW_SHIBATA,
    SWR_DITHER_NS_HIGH_SHIBATA,
    SWR_DITHER_NB,
    SwrEngine,
    SWR_ENGINE_SWR,
    SWR_ENGINE_SOXR,
    SWR_ENGINE_NB,
    SwrFilterType,
    SWR_FILTER_TYPE_CUBIC,
    SWR_FILTER_TYPE_BLACKMAN_NUTTALL,
    SWR_FILTER_TYPE_KAISER,
    SwrContext


const SWR_CH_MAX  =  32
const SWR_FLAG_RESAMPLE  =  1

# begin enum SwrDitherType
const SwrDitherType = UInt32
const SWR_DITHER_NONE  =  UInt32(0)
const SWR_DITHER_RECTANGULAR  =  UInt32(1)
const SWR_DITHER_TRIANGULAR  =  UInt32(2)
const SWR_DITHER_TRIANGULAR_HIGHPASS  =  UInt32(3)
const SWR_DITHER_NS  =  UInt32(64)
const SWR_DITHER_NS_LIPSHITZ  =  UInt32(65)
const SWR_DITHER_NS_F_WEIGHTED  =  UInt32(66)
const SWR_DITHER_NS_MODIFIED_E_WEIGHTED  =  UInt32(67)
const SWR_DITHER_NS_IMPROVED_E_WEIGHTED  =  UInt32(68)
const SWR_DITHER_NS_SHIBATA  =  UInt32(69)
const SWR_DITHER_NS_LOW_SHIBATA  =  UInt32(70)
const SWR_DITHER_NS_HIGH_SHIBATA  =  UInt32(71)
const SWR_DITHER_NB  =  UInt32(72)
# end enum SwrDitherType

# begin enum SwrEngine
const SwrEngine = UInt32
const SWR_ENGINE_SWR  =  UInt32(0)
const SWR_ENGINE_SOXR  =  UInt32(1)
const SWR_ENGINE_NB  =  UInt32(2)
# end enum SwrEngine

# begin enum SwrFilterType
const SwrFilterType = UInt32
const SWR_FILTER_TYPE_CUBIC  =  UInt32(0)
const SWR_FILTER_TYPE_BLACKMAN_NUTTALL  =  UInt32(1)
const SWR_FILTER_TYPE_KAISER  =  UInt32(2)
# end enum SwrFilterType

const SwrContext = Nothing
